Project-503-Capstone-Project-Blog-Page-App-(Django)-on-AWS-Environment/src/blog/urls.py
from django.urls import path
from .views import post_list, post_create, post_detail, post_update, post_delete, like


app_name = "blog"
urlpatterns = [
    path("", post_list, name="list"),
    path("create/", post_create, name="create"),
    path("<str:slug>/", post_detail, name="detail"),
    path("<str:slug>/update/", post_update, name="update"),
    path("<str:slug>/delete/", post_delete, name="delete"),
    path("<str:slug>/like/", like, name="like"),
]

Project-503-Capstone-Project-Blog-Page-App-(Django)-on-AWS-Environment/src/cblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls")),
    path("users/", include("users.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Project-503-Capstone-Project-Blog-Page-App-(Django)-on-AWS-Environment/src/blog/models.py
from django.db import models
from django.contrib.auth.models import User


def user_directory_path(instance, filename):
    return 'blog/{0}/{1}'.format(instance.author.id, filename)


# class Category(models.Model):
#     name = models.CharField(max_length=100)

    # class Meta:
    #     verbose_name_plural = "Categories"

    # def __str__(self):
    #     return self.name


class Post(models.Model):
    OPTIONS = (
        ('d', 'Draft'),
        ('p', 'Published')
    )
    CATEGORY_OPT = (
        ('e', 'Entertainment'),
        ('m', 'Music'),
        ('i', 'IT')
    )
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(
        upload_to=user_directory_path, default='django.jpg')
    category = models.CharField(max_length=15, choices=CATEGORY_OPT, default='e')
    publish_date = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=OPTIONS, default='d')
    slug = models.SlugField(blank=True, unique=True)  # how-to-learn-django

    def __str__(self):
        return self.title

    def comment_count(self):
        return self.comment_set.all().count()

    def view_count(self):
        return self.postview_set.all().count()

    def like_count(self):
        return self.like_set.all().count()

    def comments(self):
        return self.comment_set.all()


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __str__(self):
        return self.user.username


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

Project-503-Capstone-Project-Blog-Page-App-(Django)-on-AWS-Environment/src/blog/forms.py
from django import forms
from django.db.models import fields
from .models import Post, Comment


class PostForm(forms.ModelForm):
    status = forms.ChoiceField(choices=Post.OPTIONS)
    category = forms.ChoiceField(choices=Post.CATEGORY_OPT)

    class Meta:
        model = Post
        fields = (
            'title',
            'content',
            'image',
            'category',
            'status',
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

Project-503-Capstone-Project-Blog-Page-App-(Django)-on-AWS-Environment/src/blog/views.py
# from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from .models import Post, Like, PostView
from .forms import CommentForm, PostForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def post_list(request):
    qs = Post.objects.filter(status='p')
    context = {
        "object_list": qs
    }
    return render(request, "blog/post_list.html", context)


@login_required()
def post_create(request):
    # form = PostForm(request.POST or None, request.FILES or None)

    form = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, "Post created succesfully!")
            return redirect("blog:list")
    context = {
        'form': form
    }
    return render(request, "blog/post_create.html", context)


def post_detail(request, slug):
    # print(request.get_host())
    # print(slug)
    # Post.objects.get(slug=learn-drf-3c78be2186)
    # slug = learn-drf-3c78be2186
    form = CommentForm()
    obj = get_object_or_404(Post, slug=slug)
    if request.user.is_authenticated:
        PostView.objects.create(user=request.user, post=obj)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid:
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = obj
            comment.save()
            return redirect("blog:detail", slug=slug)
            # return redirect(request.path)
    context = {
        "object": obj,
        "form": form
    }
    return render(request, "blog/post_detail.html", context)


@login_required()
def post_update(request, slug):
    obj = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=obj)
    if request.user != obj.author:
        messages.warning(request, "You're not a writer of this post")
        return redirect('blog:list')
    if form.is_valid():
        form.save()
        messages.success(request, "Post updated!!")
        return redirect("blog:list")

    context = {
        "object": obj,
        "form": form
    }
    return render(request, "blog/post_update.html", context)


@login_required()
def post_delete(request, slug):
    obj = get_object_or_404(Post, slug=slug)

    if request.user.id != obj.author.id:
        messages.warning(request, "You're not a writer of this post")
        return redirect('blog:list')
    if request.method == "POST":
        obj.delete()
        messages.success(request, "Post deleted!!")
        return redirect("blog:list")
    context = {
        "object": obj
    }
    return render(request, "blog/post_delete.html", context)


@login_required()
def like(request, slug):
    if request.method == "POST":
        obj = get_object_or_404(Post, slug=slug)
        like_qs = Like.objects.filter(user=request.user, post=obj)
        if like_qs:
            like_qs.delete()
        else:
            Like.objects.create(user=request.user, post=obj)
        return redirect('blog:detail', slug=slug)
    return redirect('blog:detail', slug=slug)

Project-503-Capstone-Project-Blog-Page-App-(Django)-on-AWS-Environment/src/blog/templates/blog/post_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Blog Post</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-outline-info">Post</button>
        </form>
    </div>
</div>

{% endblock content %}

Project-503-Capstone-Project-Blog-Page-App-(Django)-on-AWS-Environment/src/blog/templates/blog/post_delete.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="row mt-5">
    <div class="col-md-6">
        <div class="card card-body">
            <p>Are you sure you want to delete "{{object}}"?</p>

            <form action=" " method="POST">
                {% csrf_token %}
                <a class="btn btn-warning" href="{% url 'blog:list' %}">Cancel</a>
                <input class="btn btn-danger" type="submit" name="Confirm" />
            </form>

        </div>
    </div>
</div>
{% endblock %}

Project-503-Capstone-Project-Blog-Page-App-(Django)-on-AWS-Environment/src/blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container card" style="width: 40rem;">
    <img src="{{ object.image.url }}" class="card-img-top" alt="post_image">
    <div class="card-body">
        <h2 class="card-title">{{ object.title }}</h2>
        <hr>
        <div>
            <span><i class="far fa-comment-alt ml-2"></i></i> {{ object.comment_count }}</span>
            <span><i class="fas fa-eye ml-2"></i> {{ object.view_count }}</span>
            <span><i class="far fa-heart ml-2"></i> {{ object.like_count }}</span>
            <span class="float-right"> <small>Posted {{ object.publish_date|timesince }} ago.</small> </span>
        </div>
        <hr>
        <p class="card-text">{{ object.content }}.</p>
        <hr>
        <div>
            <h4>Enjoy this post? Give it a LIKE!!</h4>
        </div>

        <div>
            <form action="{% url 'blog:like' object.slug %}" method="POST">

                {% csrf_token %}
                <input type="hidden" name="post">
                <input type="hidden" name="user">


                <button type="submit"><i class="far fa-heart fa-lg"></i></button>
                {{object.like_count }}
            </form>
            <hr>
            <!-- {% if user.is_authenticated %} -->
            <h4>Leave a comment below</h4>
            <form action="" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-secondary btn-sm mt-1 mb-1">SEND</button>
            </form>
            <hr>
            <h4>Comments</h4>
            {% for comment in object.comments %}
            <div>
                <p>
                    <small><b>Comment by {{user.username}}</b></small> - <small>{{ comment.time_stamp|timesince }} ago.
                    </small>
                </p>
                <p>
                    {{ comment.content }}

                </p>
            </div>
            <hr>
            {% endfor %}
            <!-- {% else %} -->
            <!-- <a href="#" class="btn btn-primary btn-block">Login to comment</a> -->
            <!-- {% endif %} -->
        </div>

    </div>

    <div class="m-3">
        {% if user.id == object.author.id %}
        <a href="{% url 'blog:update' object.slug %}" class="btn btn-info">Edit</a>
        <a href="{% url 'blog:delete' object.slug %}" class="btn btn-danger">Delete</a>
        {% endif %}
    </div>
    {% endblock content %}

Project-503-Capstone-Project-Blog-Page-App-(Django)-on-AWS-Environment/src/blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
<h1 style="text-align: center;">Clarusway Blog</h1>
<div class="row mt-5">
    {% for obj in object_list %}
    <div class="col-4">

        <div class="card shadow p-3 mb-5 bg-white rounded" style="width: 18rem; height: 25rem;">
            <img src="{{ obj.image.url }}" class="card-img-top" alt="post_image">
            <hr>
            <div class="card-body">
                <h5 class="card-title"><a href="{% url 'blog:detail' obj.slug %}">{{obj.title}}</a></h5>
                <p class="card-text">{{obj.content|truncatechars:20}}</p>
                <p>
                    <span><i class="far fa-comment-alt ml-2"></i> {{ obj.comment_count }}</span>
                    <span><i class="fas fa-eye ml-2"></i> {{ obj.view_count }}</span>
                    <span><i class="far fa-heart ml-2"></i> {{ obj.like_count }}</span>
                <p class="card-text"><small>
                        Posted {{ obj.publish_date|timesince }} ago.
                    </small>
                </p>

                </p>
            </div>
        </div>
    </div>

    {% endfor %}
</div>
{% endblock content %}

Project-503-Capstone-Project-Blog-Page-App-(Django)-on-AWS-Environment/src/blog/templates/blog/post_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Update Post</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-outline-info">Update</button>
        </form>
    </div>
</div>

{% endblock content %}